name: unicon
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.2 <4.0.0'
dependencies: 
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  go_router: ^12.1.3
  markdown_widget: ^2.3.2+6
  url_strategy: ^0.2.0
  google_fonts: ^6.2.1
  flutter_timer_countdown: ^1.0.7
  flutter_svg: ^2.0.10+1
  flutter_carousel_widget: ^2.2.0
  section_scroll: 
    git: 
      url: https://github.com/reitmas32/section_scroll.git
      ref: main

  flutter: 
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^2.0.0
  lint: ^1.3.0
  pubspec_dependency_sorter: ^1.0.4
  flutter_test: 
    sdk: flutter
flutter: 
  assets: 
    - assets/
    - assets/speakers/
  uses-material-design: true
