# El nombre del flujo de trabajo
name: first-test

# El evento que desencadena el flujo de trabajo
on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
        - main
        - development

jobs:
  analysis:
    # El nombre del trabajo
    name: Linter Code
    runs-on: ubuntu-latest
    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
          architecture: x64
      - name: Flutter Linter
        run: dart analyze
